# Generated by Django 2.1.2 on 2018-10-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_title', models.CharField(max_length=200)),
                ('portfolio_description', models.CharField(max_length=200)),
                ('portfolio_img_src', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=200)),
                ('service_logo', models.CharField(max_length=50)),
                ('service_descripion', models.CharField(max_length=600)),
            ],
        ),
    ]
